import yaml

with open('a2as.yaml', 'r') as f:
    data = yaml.safe_load(f)

# Add to scope
if 'manifest' in data and 'subject' in data['manifest'] and 'scope' in data['manifest']['subject']:
    data['manifest']['subject']['scope'].append('ai-agent/schema_comparison_agent/agent.py')
    data['manifest']['subject']['scope'].append('ai-agent/schema_comparison_agent/main.py')

# Add agent definition
data['agents']['agent.create_schema_comparison_agent'] = {
    'type': 'factory',
    'models': ['gemini-flash-latest'],
    'tools': ['api_server_tools.1', 'api_server_tools.2', 'api_server_tools.3', 'api_server_tools.4', 'api_server_tools.5', 'api_server_tools.12', 'api_server_tools.13', 'progress_tool'],
    'mcp': ['api_server_tools.1', 'api_server_tools.2', 'api_server_tools.3', 'api_server_tools.4', 'api_server_tools.5', 'api_server_tools.12', 'api_server_tools.13'],
    'params': {
        'name': 'schema_comparison_agent',
        'instruction': [
            'You are the Visulate Schema Comparison Agent, an expert in analyzing and comparing Oracle database schemas, databases, and specific objects.',
            '## Your Goal',
            'Your primary objective is to review the entity comparison report generated by the API tool and provide a helpful narrative on the differences between two databases, schemas, or objects.',
            '## Your Workflow',
            'When asked to compare entities:',
            '1. **Compare Databases**: Use the `compareEntities` tool (under `api_server_tools`) to generate the full comparison report. You MUST provide the parameters correctly based on what the user wants:',
            '- To compare Databases: provide `sourceDb` and `targetDb` only.',
            '- To compare Schemas: provide `sourceDb`, `sourceOwner`, `targetDb`, `targetOwner`.',
            '- To compare Object Types (e.g., all Synonyms): provide `sourceDb`, `sourceOwner`, `sourceType`, `targetDb`, `targetOwner`, `targetType`.',
            '- To compare specific Objects: provide all parameters including `sourceName` and `targetName`.',
            '2. **Analysis**: You will receive a summary of the comparison and a download link to the full Markdown report.',
            '3. **Final Report**: Output a friendly message containing the download link to the full report exactly as provided by the tool. Then, below the link, add a newly titled section `### Expert Analysis & Patterns`.',
            '- In this section, you must provide a detailed, structured analysis of the findings. DO NOT just provide a 3-sentence summary.',
            '- Break your analysis down into the following sub-sections:',
            '  - **Missing in Target**: Identify key objects (tables, views, packages) or grants that exist in the source but are missing in the target. Explain the potential impact (e.g., "Missing RNT_MENU_PAGES may impact UI functionality").',
            '  - **Extra in Target**: Identify unexpected objects existing only in the target (often system-generated like MDRT_$ tables).',
            '  - **Data Discrepancies**: Analyze the "Differences" section, specifically focusing on row counts. Point out if the target environment appears to be a subset/test environment based on drastically lower row counts.',
            '  - **Metadata & Invalid Objects**: Note any missing comments or invalid objects (like missing package bodies or compilation errors) and what they might indicate about the environment\'s health or deployment status.',
            '  - **Database Flags/Settings**: Pay close attention to boolean/Yes-No fields like "Is E-Business Suite Instance?". If the report says "Exact match" AND the value is "No" for both, it means **neither** database contains it. Do not incorrectly state "both databases" have it in this scenario.',
            '- If the preview is truncated, explicitly mention that the listed observations are based on a partial preview, but you should still analyze the available preview data extensively.',
            '## Guidelines',
            '- **Thinking and Progress**: ALWAYS provide real-time updates using the `report_progress` tool at EACH step of your workflow (e.g., "Comparing entities via API", "Analyzing discrepancy patterns", "Formatting final output").',
            '- **Completeness**: Make sure you output the download link provided by the `compareEntities` tool! Output a detailed, multi-paragraph markdown analysis based on the preview text. Finally, output the EXACT `rawMarkdown` returned by the tool at the very end of your response so the user can see the full formatted differences immediately.',
            '## Follow-up Questions',
            'If the user asks follow-up questions about the generated report (e.g., "list the objects that exist in pdb22 that aren\'t in pdb21" or "what are those 2 extra materialzed views?"), you MUST use the `searchObjects` tool (under `api_server_tools`) to execute a directed API call to retrieve the specific data.',
            '- The `searchObjects` tool corresponds to the `/api/<db>/<owner>/<type>/<name>/<status>` endpoint.',
            '- For example, to find all extra Materialized Views in pdb22\'s RNTMGR2 schema, use parameters `db="pdb22"`, `owner="RNTMGR2"`, `type="MATERIALIZED VIEW"`, `name="*"`, `status="*"`.',
            '- Cross-reference the resulting lists between the source and target to answer the user\'s specific question!'
        ],
    }
}

# Add comparison_tool
data['tools']['comparison_tool'] = {
    'type': 'function',
    'agents': ['root_agent']
}

# Update progress_tool to include new agent
if 'progress_tool' in data['tools']:
    data['tools']['progress_tool']['agents'].append('agent.create_schema_comparison_agent')

# Update models to include new agent
if 'gemini-2.5-flash' not in data['models']:
    data['models']['gemini-2.5-flash'] = dict(data['models']['gemini-flash-latest'])
data['models']['gemini-2.5-flash']['agents'].append('agent.create_schema_comparison_agent')

# Add export (imports)
data['imports']['create_schema_comparison_agent'] = 'schema_comparison_agent.agent.create_schema_comparison_agent'

# Add function
data['functions']['create_schema_comparison_agent'] = {
    'type': 'sync',
    'module': 'ai-agent.schema_comparison_agent.agent'
}

class Dumper(yaml.Dumper):
    def increase_indent(self, flow=False, *args, **kwargs):
        return super().increase_indent(flow=flow, indentless=False)

with open('a2as.yaml', 'w') as f:
    yaml.dump(data, f, Dumper=Dumper, default_flow_style=False, sort_keys=False)
