CREATE OR REPLACE FORCE VIEW RNT_LOOKUP_VALUES_V
(LOOKUP_TYPE_ID, LOOKUP_TYPE_CODE, LOOKUP_VALUE_ID, LOOKUP_CODE, LOOKUP_VALUE)
AS 
select t.LOOKUP_TYPE_ID, 
       t.LOOKUP_TYPE_CODE,
       v.LOOKUP_VALUE_ID, 
       v.LOOKUP_CODE, 
       v.LOOKUP_VALUE 
from RNT_LOOKUP_TYPES t,
     RNT_LOOKUP_VALUES v
where t.LOOKUP_TYPE_ID = v.LOOKUP_TYPE_ID
/




CREATE OR REPLACE FORCE VIEW RNT_USER_ASSIGNMENTS_V
(USER_ID, USER_LOGIN, USER_NAME, IS_ACTIVE_YN, ROLE_CODE, 
 ROLE_NAME, ROLE_ID, USER_ASSIGN_ID)
AS 
select u.USER_ID, u.USER_LOGIN, u.USER_NAME, u.IS_ACTIVE_YN,
       r.ROLE_CODE, r.ROLE_NAME, r.ROLE_ID,
       a.USER_ASSIGN_ID
from RNT_USERS u,
     RNT_USER_ROLES r,
     RNT_USER_ASSIGNMENTS a
where a.ROLE_ID = r.ROLE_ID
  and a.USER_ID= u.USER_ID
/



