CREATE TABLE RNT_LOOKUP_TYPES
(
  LOOKUP_TYPE_ID           NUMBER               NOT NULL,
  LOOKUP_TYPE_CODE         VARCHAR2(30 BYTE)    NOT NULL,
  LOOKUP_TYPE_DESCRIPTION  VARCHAR2(80 BYTE)    NOT NULL
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


CREATE TABLE RNT_LOOKUP_VALUES
(
  LOOKUP_VALUE_ID  NUMBER                       NOT NULL,
  LOOKUP_CODE      VARCHAR2(80 BYTE)            NOT NULL,
  LOOKUP_VALUE     VARCHAR2(80 BYTE)                NULL,
  LOOKUP_TYPE_ID   NUMBER                       NOT NULL
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/



CREATE TABLE RNT_USER_ROLES
(
  ROLE_ID    NUMBER                             NOT NULL,
  ROLE_CODE  VARCHAR2(10 BYTE)                  NOT NULL,
  ROLE_NAME  VARCHAR2(30 BYTE)                  NOT NULL
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/

COMMENT ON TABLE RNT_USER_ROLES IS 'Roles for users.'
/

COMMENT ON COLUMN RNT_USER_ROLES.ROLE_ID IS 'Role ID'
/

COMMENT ON COLUMN RNT_USER_ROLES.ROLE_CODE IS 'Internal code'
/

COMMENT ON COLUMN RNT_USER_ROLES.ROLE_NAME IS 'Display name'
/


CREATE TABLE RNT_USERS
(
  USER_ID        NUMBER                         NOT NULL,
  USER_LOGIN     VARCHAR2(20 BYTE)              NOT NULL,
  USER_NAME      VARCHAR2(50 BYTE)              NOT NULL,
  USER_PASSWORD  VARCHAR2(64 BYTE)              NOT NULL,
  IS_ACTIVE_YN   VARCHAR2(1 BYTE)               NOT NULL
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/

COMMENT ON TABLE RNT_USERS IS 'User who using system'
/

COMMENT ON COLUMN RNT_USERS.USER_ID IS 'User ID'
/

COMMENT ON COLUMN RNT_USERS.USER_LOGIN IS 'Login for user'
/

COMMENT ON COLUMN RNT_USERS.USER_NAME IS 'User name '
/

COMMENT ON COLUMN RNT_USERS.USER_PASSWORD IS 'User password'
/

COMMENT ON COLUMN RNT_USERS.IS_ACTIVE_YN IS 'Y is user is active, else N'
/


CREATE TABLE RNT_USER_ASSIGNMENTS
(
  USER_ASSIGN_ID  NUMBER                        NOT NULL,
  ROLE_ID         NUMBER                        NOT NULL,
  USER_ID         NUMBER                        NOT NULL
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/

COMMENT ON TABLE RNT_USER_ASSIGNMENTS IS 'User assignments on role. '
/

COMMENT ON COLUMN RNT_USER_ASSIGNMENTS.USER_ASSIGN_ID IS 'Assignment ID'
/

COMMENT ON COLUMN RNT_USER_ASSIGNMENTS.ROLE_ID IS 'Role ID'
/

COMMENT ON COLUMN RNT_USER_ASSIGNMENTS.USER_ID IS 'User ID'
/



CREATE UNIQUE INDEX RNT_LOOKUP_TYPES_PK ON RNT_LOOKUP_TYPES
(LOOKUP_TYPE_ID)
LOGGING
NOPARALLEL
/


CREATE UNIQUE INDEX RNT_LOOKUP_TYPES_U1 ON RNT_LOOKUP_TYPES
(LOOKUP_TYPE_CODE)
LOGGING
NOPARALLEL
/


CREATE UNIQUE INDEX RNT_LOOKUP_VALUES_PK ON RNT_LOOKUP_VALUES
(LOOKUP_VALUE_ID)
LOGGING
NOPARALLEL
/


CREATE UNIQUE INDEX RNT_LOOKUP_VALUES_U1 ON RNT_LOOKUP_VALUES
(LOOKUP_TYPE_ID, LOOKUP_CODE)
LOGGING
NOPARALLEL
/


CREATE UNIQUE INDEX RNT_USER_PK ON RNT_USERS
(USER_ID)
LOGGING
NOPARALLEL
/


CREATE UNIQUE INDEX RNT_USER_U1 ON RNT_USERS
(USER_LOGIN)
LOGGING
NOPARALLEL
/


CREATE UNIQUE INDEX RNT_USER_ASSIGNMENTS_PK ON RNT_USER_ASSIGNMENTS
(USER_ASSIGN_ID)
LOGGING
NOPARALLEL
/


CREATE UNIQUE INDEX RNT_USER_ASSIGNMENTS_U1 ON RNT_USER_ASSIGNMENTS
(ROLE_ID, USER_ID)
LOGGING
NOPARALLEL
/

alter table RNT_USER_ROLES
add constraint RNT_USER_ROLES_PK primary key (ROLE_ID)
LOGGING
NOPARALLEL
/


CREATE UNIQUE INDEX RNT_USER_ROLES_U1 ON RNT_USER_ROLES
(ROLE_CODE)
LOGGING
NOPARALLEL
/


